### ISSUE TITLE
Add Nortek S&C HUSBZB-1 controller stick

### ISSUE THREAD

**Issue by guymcswain** [mozilla-iot/zwave-adapter#10]
As interim fix please add these port properties to `isZWavePort()` 

- port.vendorId === '10c4'
- port.productId === '8a2a'

**Comment by guymcswain** [comment]
This USB stick has dual controllers for ZWave and ZigBee.  Both controllers reside behind a usb-serial bridge with identical `port.vendorId` and `port.productId`.  I have not used ZigBee but I would expect this code to break there if a similar 'enumeration' method is used.  The permanent fix should avoid using the usb-serial bridge to enumerate the attached controllers.

**Comment by mrstegeman** [comment]
@guymcswain Can you confirm that #11 fixes the issue?

**Comment by guymcswain** [comment]
By examination, yes, this is how I patched my code to get to working.  I would be happy to rebuild from a merged repo of the gateway or show me how to do this.

**Comment by mrstegeman** [comment]
@guymcswain I've released an updated package. If you go into _Settings->Add-ons_, you can remove the old Z-Wave adapter and then get the updated version by clicking the + at the bottom right.
