### ISSUE TITLE
Adding support for Aeotec Wallmote [Quad]

### ISSUE THREAD

**Issue by nyergler** [mozilla-iot/zwave-adapter#28]
I've successfully added my Aeotec Smart Switch to my gateway, and would like to add a [Wallmote Quad](https://aeotec.freshdesk.com/support/solutions/articles/6000166184-wallmote-quad-technical-specifications-) to control it as a "wall switch". Watching the logs when I try to pair it, it appears to identify as a slave device/controller with multiple channels (log attached: [ozw_log_add_wallmote.txt](https://github.com/mozilla-iot/zwave-adapter/files/2164555/ozw_log_add_wallmote.txt)). It's recognized by Gateway as an "unknown thing".

After registration, pressing one of the buttons logs the following message:

```
2018-07-05 00:24:06.701 Info, Node007, Received Central Scene set from node 7: scene id=3 in 0 seconds. Sending event notification.
2018-07-05 00:24:06.701 Warning, Node007, No ValueID created for Scene 3
2018-07-05 00:24:12.331 Detail, Node007,   Received: 0x01, 0x0b, 0x00, 0x04, 0x00, 0x07, 0x05, 0x5b, 0x03, 0x25, 0x00, 0x04, 0x8b
2018-07-05 00:24:12.336 Detail, 
```

I suspect that `zwave-classifier.js` needs to be extended to understand the concept of a wall switch and (possibly) a multi-channel device. I'm up for taking a pass at that, but wonder if any one else has suggestions/guidance about where to begin. The thing I'm fuzziest on at the moment is how "events" on the device wind up mapping to inputs for rules once it's registered. Maybe the "scene" is a property that can be observed?

**Comment by nyergler** [comment]
Thanks, @dhylands, that's a helpful script to know about. I run it against my gateway with the wallmote paired and this is what I get for it: 

```json
   {
        "actions": {},
        "adapterId": "zwave-e3969162",
        "description": "",
        "events": {},
        "id": "zwave-e3969162-7",
        "lastStatus": "sleeping",
        "name": "",
        "pluginId": "zwave-adapter",
        "properties": {},
        "type": "thing",
        "zwClasses": [
            132,
            32
        ],
        "zwInfo": {
            "location": "",
            "manufacturer": "",
            "manufacturerId": "",
            "nodeId": 7,
            "product": "",
            "productId": "",
            "productType": "",
            "type": ""
        },
        "zwValues": {
            "7-132-1-0": {
                "class_id": 132,
                "genre": "system",
                "help": "",
                "index": 0,
                "instance": 1,
                "is_polled": false,
                "label": "Wake-up Interval",
                "max": 2147483647,
                "min": -2147483648,
                "node_id": 7,
                "read_only": false,
                "type": "int",
                "units": "Seconds",
                "value": 3600,
                "value_id": "7-132-1-0",
                "write_only": false
            },
            "7-32-1-0": {
                "class_id": 32,
                "genre": "basic",
                "help": "",
                "index": 0,
                "instance": 1,
                "is_polled": false,
                "label": "Basic",
                "max": 255,
                "min": 0,
                "node_id": 7,
                "read_only": false,
                "type": "byte",
                "units": "",
                "value": 0,
                "value_id": "7-32-1-0",
                "write_only": false
            }
        }
    }
```

This makes me think that instead of watching property changes I need to be listening for events coming from the device. (It occurs to me that the wallmote switch differs from, say, the smart switch in that it basically acts as an input: there isn't state to set from the gateway, but it could [potentially] trigger other things to change state.)

Reading the adapter source, I _think_ the most likely place presses would get registered are on scene event. From the log line above, I'm wondering if I need to configure the node before it relays the scene events to the adapter code. Maybe the classifier could figure out how many channels the device has and add events for those that rules could trigger off of?

**Comment by dhylands** [comment]
It looks like your wallmote uses COMMAND_CLASS_BASIC. I'm not familiar with this particular command class. Reading the zwave spec it looks like an "association destination" needs to be set and this will determine where the button press notifications will go. I think that you want to set this to go to the dongle (which is node 1).

That's about all the advice I can offer right now since I haven't used this type of device before.

**Comment by coreyo** [comment]
This device also supports zwave scenes. see #46

**Comment by dhylands** [comment]
I just ordered a WallMote and another wall switch to see what's required to get these to work. I did add some support for central scenes for this device: http://www.gocontrol.com/detail.php?productId=12

That required a change to one of the open-zwave config files, which is still pending in a PR:
https://github.com/OpenZWave/open-zwave/pull/1668

**Comment by dhylands** [comment]
0.7.1 of the zwave-adapter now supports the Wallmote quad
