### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by mrstegeman** [mozilla-iot/zwave-adapter#36]
This adapter's dependencies need to be updated in order for it to work with Node v10.

* `serialport` has had a major version bump, but it _shouldn't_ cause any issues. [CHANGELOG](https://github.com/node-serialport/node-serialport/blob/master/packages/serialport/CHANGELOG.md)
* `openzwave-shared` has had a minor version bump, but there were (potentially) breaking changes to `enablePoll()` and `disablePoll()` (see [README](https://github.com/OpenZWave/node-openzwave-shared))

**Comment by mrstegeman** [comment]
@dhylands I'm happy to make a PR, but I only have one smart plug to test with, nothing else.

**Comment by dhylands** [comment]
If you want to create the PR, I'd be happy to test it.
