### ISSUE TITLE
Zooz 4-in-1 shows up without properties

### ISSUE THREAD

**Issue by hobinjk** [mozilla-iot/zwave-adapter#50]
It shows up in OZW_log as Node003 but isn't in zwcfg for some reason. Attached OZW_log in case it's useful
[OZW_Log.txt](https://github.com/mozilla-iot/zwave-adapter/files/2857166/OZW_Log.txt)

**Comment by dhylands** [comment]
I suspect that this should work better with the 0.7.1 release.
