### ISSUE TITLE
device disconnected after gateway reboot

### ISSUE THREAD

**Issue by vincentserpoul** [mozilla-iot/zwave-adapter#58]
I've deployed a gateway as a test and added a few devices, 3 zigbee and 1 zwave.
All the devices were detected and connected when installed.

When I restarted my gateway, all the zigbee devices were reconnected, but the zwave device did not reconnect.

The [device](https://aeotec.com/z-wave-door-window-sensor) is not listed in the list of compatible devices, it was connected but only reporting the battery left on the device but that's another issue.

1. Is there anyway to help debug this zwave connection issue?
2. What is the usual way of doing to enable more data on a specific device?

**Comment by dhylands** [comment]
If you go into Settings->Addons and click Configure for the zwave adapter, there is a debug field where you can enter one or more of the words classifier, flow, or node. You can use commas to seperate multiple words. This will cause additional information to be displayed in the log.

You can also look in the /home/pi/.mozilla-iot/log directory and you should be able to see a file with a name like zwcfg_0x99999999.xml (where the 9's will be the ID of your dongle) and it should contain the devices that the dongle has paired.
