### ISSUE TITLE
ZWave adapter classifier regression - Smart Switch 6 classified as a light

### ISSUE THREAD

**Issue by tlexii** [mozilla-iot/zwave-adapter#67]
Since this [commit](https://github.com/mozilla-iot/zwave-adapter/commit/8b8033eccfe736c6b3abea096ae6ae5eb7ded038) classifies any of these types as a bulb, Smart Switch 6 has converted to a bulb (it has coloured leds built in).

`      case GENERIC_TYPE.SWITCH_BINARY:`
`      case GENERIC_TYPE.SWITCH_MULTILEVEL:`
`      {`
`        if (colorCapabilitiesValueId) {`
`          this.initLight(node, colorCapabilitiesValueId, levelValueId);`
`          return;`
`        }`

**Comment by dhylands** [comment]
This should now be fixed in 0.7.4 of the zwaveadapter

**Comment by tlexii** [comment]
Thanks
