### ISSUE TITLE
Add support for motion sensors

### ISSUE THREAD

**Issue by dhylands** [mozilla-iot/zwave-adapter#7]
This originally came in through the discourse mailing list: https://discourse.mozilla.org/t/zwave-support-neo-coolcam-motion-sensor/25356

The user sent me his log files which I've attached here. It looks like the sensor is being partially recognized (as a binary sensor).

The algorithm for selecting the default name also did a less than stellar job here, coming up with zwave-f1d3204d-6-Battery Level

[OZW_Log.txt](https://github.com/mozilla-iot/zwave-adapter/files/1711983/OZW_Log.txt)
[run-app.log](https://github.com/mozilla-iot/zwave-adapter/files/1711984/run-app.log)

**Comment by mmjjb** [comment]
Not being followed up?

**Comment by dhylands** [comment]
I should be adding support for that soon.

**Comment by Beejeedeb** [comment]
Hey,

I use the Neo Coolcam Motion detector. It works without problems. Out of the box.

![Neo Coolcam motion sensor](https://user-images.githubusercontent.com/51539492/60741228-ea6df280-9f68-11e9-9a67-ec33b75c7d45.PNG)

The problem has been solved for this mortion detector.
