### ISSUE TITLE
Update 0.9.2 don't provide enough information on sensors (Fibaro Motion/Fibaro WallPlug)

### ISSUE THREAD

**Issue by tomislavboros** [mozilla-iot/zwave-adapter#88]
After mozilla firmware update to version 0.9.2 of zwave adapter my Zwave sensors (Fibaro motion sensor FGMS-001 ZW5 v3.2, and Fibaro wall plug FGWPF-101) don't provide me enough informations ... example is Fibaro Wall plug don't provide POWER CONSUMPTION (property "instantaneousPower")?!

Or maybe is there any possibility to rollback adapter version?

Thank you for understanding
Tomislav

**Comment by dhylands** [comment]
The latest version of the zwave adapter 0.9.3 should restore the power consumption for the wall sensors.

Can you describe the issue with the motion sensor?

**Comment by tomislavboros** [comment]
I saw that 0.9.3 version restore some power consumption property.
Motion sensor had a bug with motion detection - temper ability was not checked ("motion" property) but after re-inclusion, and 0.9.3 update everything works fine.
Right now all sensors work as expected.

Thanks for your help and understanding,
